Repository zackotterstrom/SAoT, pull requests merged in 2018-10, with the labels that each got.

#23 added modal for tweet
  src/views/Tweets.vue
Labels: enhancement

#29 18-loading-icon
  src/App.vue
  src/components/Header.vue
  src/components/LoadingIcon.vue
  src/components/Search.vue
  src/components/TweetList.vue
  src/main.ts
  src/views/Home.vue
  src/views/Tweets.vue
Labels: new

#25 Changes the vue watermark
  public/favicon.ico
  public/index.html
Labels: enhancement

#33 resolved #30
  src/App.vue
  src/components/Search.vue
  src/components/TweetList.vue
  src/views/Home.vue
  src/views/Tweets.vue
Labels: enhancement

#35 resolved #32
  src/components/Search.vue
Labels: enhancement

#37 bug fixed #32
  src/components/Search.vue
Labels: bug

#38 bug fixed #32
  src/components/Search.vue
Labels: bug

#39 implemented #31
  src/views/Tweets.vue
Labels: enhancement

#42 40 develop
  src/components/LoadingIcon.vue
  src/components/TweetDetails.vue
  src/views/Tweets.vue
Labels: enhancement

#49 fix #45
  src/components/TweetDetails.vue
Labels: bug

#52 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#58 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#54 Create LICENSE
  LICENSE
Labels: enhancement

#53 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#56 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#62 Navbar done
  src/components/Header.vue
Labels: enhancement

#61 Update issue templates
  .github/ISSUE_TEMPLATE/other-issue.md
Labels: enhancement

#59 loading icon added to summary
  src/components/TweetDetails.vue
  src/components/TweetSummary.vue
  src/views/Tweets.vue
Labels: enhancement

#60 36 advanced search
  src/components/Search.vue
  src/gcloud/sentiment-analysis.js
  src/gcloud/tweets.js
  src/router.ts
  src/views/SearchAdvanced.vue
Labels: enhancement, new

#69 Expose analyse and twitter search
  src/api.ts
  src/components/TweetDetails.vue
  src/main.ts
  src/my-property.ts
  src/views/Tweets.vue
Labels: enhancement

#68 47 technical about
  package.json
  src/App.vue
  src/assets/IMG_3299.jpg
  src/assets/IMG_3301.jpg
  src/assets/IMG_3302.jpg
  src/assets/IMG_3305.jpg
  src/assets/about_us.jpg
  src/components/AboutInfo.vue
  src/router.ts
  src/views/about.vue
  vue.config.js
Labels: enhancement

#71 closes #65
  src/components/TweetDetails.vue
  src/components/TweetList.vue
  src/views/Tweets.vue
Labels: enhancement

#90 fixed #73
  src/components/TweetDetails.vue
Labels: bug

#94 added magnitudeToText
  src/api.ts
  src/components/TweetDetails.vue
  src/components/TweetSummary.vue
  src/main.ts
  src/views/Tweets.vue
Labels: enhancement, new

#95 closes #78
  src/api.ts
  src/components/Search.vue
  src/components/TweetDetails.vue
  src/components/TweetList.vue
  src/components/TweetSummary.vue
  src/views/Tweets.vue
Labels: bug

#98 Support all languages.
  src/api.ts
  src/gcloud/sentiment-analysis.js
  src/views/Tweets.vue
Labels: enhancement
